// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_A_xy_im
NumericMatrix cpp_A_xy_im(NumericVector fi_xy, int k);
RcppExport SEXP _binsensate_cpp_A_xy_im(SEXP fi_xySEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type fi_xy(fi_xySEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_A_xy_im(fi_xy, k));
    return rcpp_result_gen;
END_RCPP
}
// cpp_A_xy_im_sparse
Eigen::SparseMatrix<double> cpp_A_xy_im_sparse(NumericVector fi_xy, int k);
RcppExport SEXP _binsensate_cpp_A_xy_im_sparse(SEXP fi_xySEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type fi_xy(fi_xySEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_A_xy_im_sparse(fi_xy, k));
    return rcpp_result_gen;
END_RCPP
}
// cpp_Ainv_xy_im
NumericMatrix cpp_Ainv_xy_im(NumericVector fi_xy, int k);
RcppExport SEXP _binsensate_cpp_Ainv_xy_im(SEXP fi_xySEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type fi_xy(fi_xySEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_Ainv_xy_im(fi_xy, k));
    return rcpp_result_gen;
END_RCPP
}
// cpp_A_xy_zinf_sparse
Eigen::SparseMatrix<double> cpp_A_xy_zinf_sparse(NumericVector fi_xy, int k);
RcppExport SEXP _binsensate_cpp_A_xy_zinf_sparse(SEXP fi_xySEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type fi_xy(fi_xySEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_A_xy_zinf_sparse(fi_xy, k));
    return rcpp_result_gen;
END_RCPP
}
// cpp_A_xy_zinf
NumericMatrix cpp_A_xy_zinf(NumericVector fi_xy, int k);
RcppExport SEXP _binsensate_cpp_A_xy_zinf(SEXP fi_xySEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type fi_xy(fi_xySEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_A_xy_zinf(fi_xy, k));
    return rcpp_result_gen;
END_RCPP
}
// cpp_Ainv_xy_zinf
NumericMatrix cpp_Ainv_xy_zinf(NumericVector fi_xy, int k);
RcppExport SEXP _binsensate_cpp_Ainv_xy_zinf(SEXP fi_xySEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type fi_xy(fi_xySEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_Ainv_xy_zinf(fi_xy, k));
    return rcpp_result_gen;
END_RCPP
}
// cpp_fi_grad_ZINF
NumericVector cpp_fi_grad_ZINF(NumericVector fi, NumericVector pr);
RcppExport SEXP _binsensate_cpp_fi_grad_ZINF(SEXP fiSEXP, SEXP prSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type fi(fiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pr(prSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_fi_grad_ZINF(fi, pr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_fi_grad_IM
NumericVector cpp_fi_grad_IM(NumericMatrix Ainv, NumericVector neg_idx, NumericVector pr, NumericVector fi, int verbose);
RcppExport SEXP _binsensate_cpp_fi_grad_IM(SEXP AinvSEXP, SEXP neg_idxSEXP, SEXP prSEXP, SEXP fiSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Ainv(AinvSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type neg_idx(neg_idxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pr(prSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type fi(fiSEXP);
    Rcpp::traits::input_parameter< int >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_fi_grad_IM(Ainv, neg_idx, pr, fi, verbose));
    return rcpp_result_gen;
END_RCPP
}
// cpp_hess_lambda
NumericMatrix cpp_hess_lambda(NumericVector pz, NumericVector px_z, int p);
RcppExport SEXP _binsensate_cpp_hess_lambda(SEXP pzSEXP, SEXP px_zSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pz(pzSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type px_z(px_zSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_hess_lambda(pz, px_z, p));
    return rcpp_result_gen;
END_RCPP
}
// cpp_hess_mu
NumericMatrix cpp_hess_mu(NumericVector pz, NumericVector px_z, NumericVector py_x0z, NumericVector py_x1z, int p);
RcppExport SEXP _binsensate_cpp_hess_mu(SEXP pzSEXP, SEXP px_zSEXP, SEXP py_x0zSEXP, SEXP py_x1zSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pz(pzSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type px_z(px_zSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type py_x0z(py_x0zSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type py_x1z(py_x1zSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_hess_mu(pz, px_z, py_x0z, py_x1z, p));
    return rcpp_result_gen;
END_RCPP
}
// cpp_idx
LogicalVector cpp_idx(int x, int a, int b, int dim);
RcppExport SEXP _binsensate_cpp_idx(SEXP xSEXP, SEXP aSEXP, SEXP bSEXP, SEXP dimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type a(aSEXP);
    Rcpp::traits::input_parameter< int >::type b(bSEXP);
    Rcpp::traits::input_parameter< int >::type dim(dimSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_idx(x, a, b, dim));
    return rcpp_result_gen;
END_RCPP
}
// cpp_scaling_2d
NumericVector cpp_scaling_2d(NumericMatrix Sigma);
RcppExport SEXP _binsensate_cpp_scaling_2d(SEXP SigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Sigma(SigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_scaling_2d(Sigma));
    return rcpp_result_gen;
END_RCPP
}
// cpp_hess_sigma
NumericMatrix cpp_hess_sigma(NumericVector pz, IntegerVector idx, int p);
RcppExport SEXP _binsensate_cpp_hess_sigma(SEXP pzSEXP, SEXP idxSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pz(pzSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type idx(idxSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_hess_sigma(pz, idx, p));
    return rcpp_result_gen;
END_RCPP
}
// cpp_p_z
NumericVector cpp_p_z(NumericVector lambda);
RcppExport SEXP _binsensate_cpp_p_z(SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_p_z(lambda));
    return rcpp_result_gen;
END_RCPP
}
// cpp_idx_to_bit
NumericVector cpp_idx_to_bit(IntegerVector idx, int dim);
RcppExport SEXP _binsensate_cpp_idx_to_bit(SEXP idxSEXP, SEXP dimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type idx(idxSEXP);
    Rcpp::traits::input_parameter< int >::type dim(dimSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_idx_to_bit(idx, dim));
    return rcpp_result_gen;
END_RCPP
}
// cpp_bit_to_idx_mat
NumericVector cpp_bit_to_idx_mat(NumericMatrix bit);
RcppExport SEXP _binsensate_cpp_bit_to_idx_mat(SEXP bitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type bit(bitSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_bit_to_idx_mat(bit));
    return rcpp_result_gen;
END_RCPP
}
// cpp_bit_to_idx
int cpp_bit_to_idx(NumericVector bit);
RcppExport SEXP _binsensate_cpp_bit_to_idx(SEXP bitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type bit(bitSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_bit_to_idx(bit));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_binsensate_cpp_A_xy_im", (DL_FUNC) &_binsensate_cpp_A_xy_im, 2},
    {"_binsensate_cpp_A_xy_im_sparse", (DL_FUNC) &_binsensate_cpp_A_xy_im_sparse, 2},
    {"_binsensate_cpp_Ainv_xy_im", (DL_FUNC) &_binsensate_cpp_Ainv_xy_im, 2},
    {"_binsensate_cpp_A_xy_zinf_sparse", (DL_FUNC) &_binsensate_cpp_A_xy_zinf_sparse, 2},
    {"_binsensate_cpp_A_xy_zinf", (DL_FUNC) &_binsensate_cpp_A_xy_zinf, 2},
    {"_binsensate_cpp_Ainv_xy_zinf", (DL_FUNC) &_binsensate_cpp_Ainv_xy_zinf, 2},
    {"_binsensate_cpp_fi_grad_ZINF", (DL_FUNC) &_binsensate_cpp_fi_grad_ZINF, 2},
    {"_binsensate_cpp_fi_grad_IM", (DL_FUNC) &_binsensate_cpp_fi_grad_IM, 5},
    {"_binsensate_cpp_hess_lambda", (DL_FUNC) &_binsensate_cpp_hess_lambda, 3},
    {"_binsensate_cpp_hess_mu", (DL_FUNC) &_binsensate_cpp_hess_mu, 5},
    {"_binsensate_cpp_idx", (DL_FUNC) &_binsensate_cpp_idx, 4},
    {"_binsensate_cpp_scaling_2d", (DL_FUNC) &_binsensate_cpp_scaling_2d, 1},
    {"_binsensate_cpp_hess_sigma", (DL_FUNC) &_binsensate_cpp_hess_sigma, 3},
    {"_binsensate_cpp_p_z", (DL_FUNC) &_binsensate_cpp_p_z, 1},
    {"_binsensate_cpp_idx_to_bit", (DL_FUNC) &_binsensate_cpp_idx_to_bit, 2},
    {"_binsensate_cpp_bit_to_idx_mat", (DL_FUNC) &_binsensate_cpp_bit_to_idx_mat, 1},
    {"_binsensate_cpp_bit_to_idx", (DL_FUNC) &_binsensate_cpp_bit_to_idx, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_binsensate(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
