// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_A_xy_im
NumericMatrix cpp_A_xy_im(NumericVector fi_xy, int k);
RcppExport SEXP _binsensate_cpp_A_xy_im(SEXP fi_xySEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type fi_xy(fi_xySEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_A_xy_im(fi_xy, k));
    return rcpp_result_gen;
END_RCPP
}
// cpp_Ainv_xy_im
NumericMatrix cpp_Ainv_xy_im(NumericVector fi_xy, int k);
RcppExport SEXP _binsensate_cpp_Ainv_xy_im(SEXP fi_xySEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type fi_xy(fi_xySEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_Ainv_xy_im(fi_xy, k));
    return rcpp_result_gen;
END_RCPP
}
// cpp_A_xy_zinf
NumericMatrix cpp_A_xy_zinf(NumericVector fi_xy, int k);
RcppExport SEXP _binsensate_cpp_A_xy_zinf(SEXP fi_xySEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type fi_xy(fi_xySEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_A_xy_zinf(fi_xy, k));
    return rcpp_result_gen;
END_RCPP
}
// cpp_Ainv_xy_zinf
NumericMatrix cpp_Ainv_xy_zinf(NumericVector fi_xy, int k);
RcppExport SEXP _binsensate_cpp_Ainv_xy_zinf(SEXP fi_xySEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type fi_xy(fi_xySEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_Ainv_xy_zinf(fi_xy, k));
    return rcpp_result_gen;
END_RCPP
}
// cpp_fi_grad
NumericVector cpp_fi_grad(NumericMatrix Ainv, NumericVector neg_idx, NumericVector pr, NumericVector fi, int verbose);
RcppExport SEXP _binsensate_cpp_fi_grad(SEXP AinvSEXP, SEXP neg_idxSEXP, SEXP prSEXP, SEXP fiSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Ainv(AinvSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type neg_idx(neg_idxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pr(prSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type fi(fiSEXP);
    Rcpp::traits::input_parameter< int >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_fi_grad(Ainv, neg_idx, pr, fi, verbose));
    return rcpp_result_gen;
END_RCPP
}
// cpp_idx
LogicalVector cpp_idx(int x, int a, int b, int dim);
RcppExport SEXP _binsensate_cpp_idx(SEXP xSEXP, SEXP aSEXP, SEXP bSEXP, SEXP dimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type a(aSEXP);
    Rcpp::traits::input_parameter< int >::type b(bSEXP);
    Rcpp::traits::input_parameter< int >::type dim(dimSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_idx(x, a, b, dim));
    return rcpp_result_gen;
END_RCPP
}
// cpp_scaling_2d
NumericVector cpp_scaling_2d(NumericMatrix Sigma);
RcppExport SEXP _binsensate_cpp_scaling_2d(SEXP SigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Sigma(SigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_scaling_2d(Sigma));
    return rcpp_result_gen;
END_RCPP
}
// cpp_hessian_2d
NumericMatrix cpp_hessian_2d(NumericVector pz, IntegerVector idx, int p);
RcppExport SEXP _binsensate_cpp_hessian_2d(SEXP pzSEXP, SEXP idxSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pz(pzSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type idx(idxSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_hessian_2d(pz, idx, p));
    return rcpp_result_gen;
END_RCPP
}
// cpp_p_z
NumericVector cpp_p_z(NumericVector lambda);
RcppExport SEXP _binsensate_cpp_p_z(SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_p_z(lambda));
    return rcpp_result_gen;
END_RCPP
}
// cpp_idx_to_bit
NumericVector cpp_idx_to_bit(IntegerVector idx, int dim);
RcppExport SEXP _binsensate_cpp_idx_to_bit(SEXP idxSEXP, SEXP dimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type idx(idxSEXP);
    Rcpp::traits::input_parameter< int >::type dim(dimSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_idx_to_bit(idx, dim));
    return rcpp_result_gen;
END_RCPP
}
// cpp_bit_to_idx_mat
NumericVector cpp_bit_to_idx_mat(NumericMatrix bit);
RcppExport SEXP _binsensate_cpp_bit_to_idx_mat(SEXP bitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type bit(bitSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_bit_to_idx_mat(bit));
    return rcpp_result_gen;
END_RCPP
}
// cpp_bit_to_idx
int cpp_bit_to_idx(NumericVector bit);
RcppExport SEXP _binsensate_cpp_bit_to_idx(SEXP bitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type bit(bitSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_bit_to_idx(bit));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_binsensate_cpp_A_xy_im", (DL_FUNC) &_binsensate_cpp_A_xy_im, 2},
    {"_binsensate_cpp_Ainv_xy_im", (DL_FUNC) &_binsensate_cpp_Ainv_xy_im, 2},
    {"_binsensate_cpp_A_xy_zinf", (DL_FUNC) &_binsensate_cpp_A_xy_zinf, 2},
    {"_binsensate_cpp_Ainv_xy_zinf", (DL_FUNC) &_binsensate_cpp_Ainv_xy_zinf, 2},
    {"_binsensate_cpp_fi_grad", (DL_FUNC) &_binsensate_cpp_fi_grad, 5},
    {"_binsensate_cpp_idx", (DL_FUNC) &_binsensate_cpp_idx, 4},
    {"_binsensate_cpp_scaling_2d", (DL_FUNC) &_binsensate_cpp_scaling_2d, 1},
    {"_binsensate_cpp_hessian_2d", (DL_FUNC) &_binsensate_cpp_hessian_2d, 3},
    {"_binsensate_cpp_p_z", (DL_FUNC) &_binsensate_cpp_p_z, 1},
    {"_binsensate_cpp_idx_to_bit", (DL_FUNC) &_binsensate_cpp_idx_to_bit, 2},
    {"_binsensate_cpp_bit_to_idx_mat", (DL_FUNC) &_binsensate_cpp_bit_to_idx_mat, 1},
    {"_binsensate_cpp_bit_to_idx", (DL_FUNC) &_binsensate_cpp_bit_to_idx, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_binsensate(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
