# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_A_xy <- function(fi_xy, k) {
    .Call('_binsensate_cpp_A_xy', PACKAGE = 'binsensate', fi_xy, k)
}

cpp_invert_A_xy <- function(A, pz, pr) {
    .Call('_binsensate_cpp_invert_A_xy', PACKAGE = 'binsensate', A, pz, pr)
}

cpp_fi_grad <- function(Ainv, neg_idx, pr, fi, verbose = 0L) {
    .Call('_binsensate_cpp_fi_grad', PACKAGE = 'binsensate', Ainv, neg_idx, pr, fi, verbose)
}

cpp_idx <- function(x, a, b, dim) {
    .Call('_binsensate_cpp_idx', PACKAGE = 'binsensate', x, a, b, dim)
}

cpp_fi_hash <- function(x, fi, dim) {
    .Call('_binsensate_cpp_fi_hash', PACKAGE = 'binsensate', x, fi, dim)
}

cpp_grad_ij <- function(rhash, i, j, k, fi, pz) {
    .Call('_binsensate_cpp_grad_ij', PACKAGE = 'binsensate', rhash, i, j, k, fi, pz)
}

cpp_scaling_2d <- function(Sigma) {
    .Call('_binsensate_cpp_scaling_2d', PACKAGE = 'binsensate', Sigma)
}

cpp_hessian_2d_degenerate <- function(pz, p) {
    .Call('_binsensate_cpp_hessian_2d_degenerate', PACKAGE = 'binsensate', pz, p)
}

cpp_hessian_2d <- function(pz, idx, p) {
    .Call('_binsensate_cpp_hessian_2d', PACKAGE = 'binsensate', pz, idx, p)
}

cpp_mu <- function(pz, p) {
    .Call('_binsensate_cpp_mu', PACKAGE = 'binsensate', pz, p)
}

cpp_p_z <- function(lambda) {
    .Call('_binsensate_cpp_p_z', PACKAGE = 'binsensate', lambda)
}

cpp_idx_to_bit <- function(idx, dim) {
    .Call('_binsensate_cpp_idx_to_bit', PACKAGE = 'binsensate', idx, dim)
}

cpp_bit_fi_hash <- function(x, fi) {
    .Call('_binsensate_cpp_bit_fi_hash', PACKAGE = 'binsensate', x, fi)
}

