# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_A_xy_im <- function(fi_xy, k) {
    .Call('_binsensate_cpp_A_xy_im', PACKAGE = 'binsensate', fi_xy, k)
}

cpp_A_xy_im_sparse <- function(fi_xy, k) {
    .Call('_binsensate_cpp_A_xy_im_sparse', PACKAGE = 'binsensate', fi_xy, k)
}

cpp_Ainv_xy_im <- function(fi_xy, k) {
    .Call('_binsensate_cpp_Ainv_xy_im', PACKAGE = 'binsensate', fi_xy, k)
}

cpp_A_xy_zinf_sparse <- function(fi_xy, k) {
    .Call('_binsensate_cpp_A_xy_zinf_sparse', PACKAGE = 'binsensate', fi_xy, k)
}

cpp_A_xy_zinf <- function(fi_xy, k) {
    .Call('_binsensate_cpp_A_xy_zinf', PACKAGE = 'binsensate', fi_xy, k)
}

cpp_Ainv_xy_zinf <- function(fi_xy, k) {
    .Call('_binsensate_cpp_Ainv_xy_zinf', PACKAGE = 'binsensate', fi_xy, k)
}

cpp_fi_grad_ZINF <- function(fi, pr) {
    .Call('_binsensate_cpp_fi_grad_ZINF', PACKAGE = 'binsensate', fi, pr)
}

cpp_fi_grad_IM <- function(Ainv, neg_idx, pr, fi, verbose = 0L) {
    .Call('_binsensate_cpp_fi_grad_IM', PACKAGE = 'binsensate', Ainv, neg_idx, pr, fi, verbose)
}

cpp_hess_lambda <- function(pz, px_z, p) {
    .Call('_binsensate_cpp_hess_lambda', PACKAGE = 'binsensate', pz, px_z, p)
}

cpp_hess_mu <- function(pz, px_z, py_x0z, py_x1z, p) {
    .Call('_binsensate_cpp_hess_mu', PACKAGE = 'binsensate', pz, px_z, py_x0z, py_x1z, p)
}

cpp_idx <- function(x, a, b, dim) {
    .Call('_binsensate_cpp_idx', PACKAGE = 'binsensate', x, a, b, dim)
}

cpp_scaling_2d <- function(Sigma) {
    .Call('_binsensate_cpp_scaling_2d', PACKAGE = 'binsensate', Sigma)
}

cpp_hess_sigma <- function(pz, idx, p) {
    .Call('_binsensate_cpp_hess_sigma', PACKAGE = 'binsensate', pz, idx, p)
}

cpp_p_z <- function(lambda) {
    .Call('_binsensate_cpp_p_z', PACKAGE = 'binsensate', lambda)
}

cpp_idx_to_bit <- function(idx, dim) {
    .Call('_binsensate_cpp_idx_to_bit', PACKAGE = 'binsensate', idx, dim)
}

cpp_bit_to_idx_mat <- function(bit) {
    .Call('_binsensate_cpp_bit_to_idx_mat', PACKAGE = 'binsensate', bit)
}

cpp_bit_to_idx <- function(bit) {
    .Call('_binsensate_cpp_bit_to_idx', PACKAGE = 'binsensate', bit)
}

