# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_A_xy_if <- function(fi_xy, k) {
    .Call('_binsensate_cpp_A_xy_if', PACKAGE = 'binsensate', fi_xy, k)
}

cpp_A_xy_if_sparse <- function(fi_xy, k) {
    .Call('_binsensate_cpp_A_xy_if_sparse', PACKAGE = 'binsensate', fi_xy, k)
}

cpp_Ainv_xy_if <- function(fi_xy, k) {
    .Call('_binsensate_cpp_Ainv_xy_if', PACKAGE = 'binsensate', fi_xy, k)
}

cpp_A_xy_zinf_sparse <- function(fi_xy, k) {
    .Call('_binsensate_cpp_A_xy_zinf_sparse', PACKAGE = 'binsensate', fi_xy, k)
}

cpp_A_xy_zinf <- function(fi_xy, k) {
    .Call('_binsensate_cpp_A_xy_zinf', PACKAGE = 'binsensate', fi_xy, k)
}

cpp_Ainv_xy_zinf <- function(fi_xy, k) {
    .Call('_binsensate_cpp_Ainv_xy_zinf', PACKAGE = 'binsensate', fi_xy, k)
}

cpp_fi_grad_ZINF <- function(fi, pr) {
    .Call('_binsensate_cpp_fi_grad_ZINF', PACKAGE = 'binsensate', fi, pr)
}

cpp_fi_grad_IF <- function(Ainv, neg_idx, pr, fi) {
    .Call('_binsensate_cpp_fi_grad_IF', PACKAGE = 'binsensate', Ainv, neg_idx, pr, fi)
}

cpp_isserlis <- function(ind, mu, Sigma0) {
    .Call('_binsensate_cpp_isserlis', PACKAGE = 'binsensate', ind, mu, Sigma0)
}

cpp_eta <- function(i, j, k, l, mu, Sigma0, p) {
    .Call('_binsensate_cpp_eta', PACKAGE = 'binsensate', i, j, k, l, mu, Sigma0, p)
}

cpp_lambda <- function(i, j, k, l, dim, p) {
    .Call('_binsensate_cpp_lambda', PACKAGE = 'binsensate', i, j, k, l, dim, p)
}

cpp_logc_ij_cts <- function(Amut, Ez, idx, Sigma0, Sig0Lam, Sig0b, p, d) {
    .Call('_binsensate_cpp_logc_ij_cts', PACKAGE = 'binsensate', Amut, Ez, idx, Sigma0, Sig0Lam, Sig0b, p, d)
}

cpp_hess_cts <- function(Amut, Ez, idx, Sigma0, Sig0Lam, Sig0b, p, d) {
    .Call('_binsensate_cpp_hess_cts', PACKAGE = 'binsensate', Amut, Ez, idx, Sigma0, Sig0Lam, Sig0b, p, d)
}

cpp_hess_cts_fast <- function(Amut, Ez, idx, Sigma0, Sig0Lam, Sig0b, p, d) {
    .Call('_binsensate_cpp_hess_cts_fast', PACKAGE = 'binsensate', Amut, Ez, idx, Sigma0, Sig0Lam, Sig0b, p, d)
}

cpp_pzw_prop <- function(Sigma, LamTw) {
    .Call('_binsensate_cpp_pzw_prop', PACKAGE = 'binsensate', Sigma, LamTw)
}

cpp_idx <- function(x, a, b, dim) {
    .Call('_binsensate_cpp_idx', PACKAGE = 'binsensate', x, a, b, dim)
}

cpp_scaling_2d <- function(Sigma) {
    .Call('_binsensate_cpp_scaling_2d', PACKAGE = 'binsensate', Sigma)
}

cpp_hess_sigma <- function(pz, idx, p) {
    .Call('_binsensate_cpp_hess_sigma', PACKAGE = 'binsensate', pz, idx, p)
}

cpp_p_z <- function(lambda) {
    .Call('_binsensate_cpp_p_z', PACKAGE = 'binsensate', lambda)
}

cpp_idx_to_bit <- function(idx, dim) {
    .Call('_binsensate_cpp_idx_to_bit', PACKAGE = 'binsensate', idx, dim)
}

cpp_bit_to_idx_mat <- function(bit) {
    .Call('_binsensate_cpp_bit_to_idx_mat', PACKAGE = 'binsensate', bit)
}

cpp_bit_to_idx <- function(bit) {
    .Call('_binsensate_cpp_bit_to_idx', PACKAGE = 'binsensate', bit)
}

